# theme = "serika-light"
# theme = "solarized_light"
# theme = "gruvbox_material_light_hard"
theme = "gruvbox_light"

[editor]
line-number = "relative"

[editor.statusline]
left = ["mode", "spinner", "file-base-name", "read-only-indicator", "file-modification-indicator"]
right = ["version-control", "diagnostics", "selections", "position", "file-encoding", "file-type"]
separator = "|"

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# swap keybinds for delete_noyank and delete to make delete_noyank the default
[keys.normal]
A-d = "delete_selection"
d = "delete_selection_noyank"
A-c = "change_selection"
c = "change_selection_noyank"

[keys.insert]
# up = "no_op"
# down = "no_op"
# left = "no_op"
# right = "no_op"
# pageup = "no_op"
# pagedown = "no_op"
# home = "no_op"
# end = "no_op"
