#!/bin/bash

# Plugins
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# PATH configuration
export PATH="/home/jwl/bin:/home/jwl/.cargo/bin:$PATH"


# ALIAS stuff
alias hx='helix'

# use exa as a better li
alias ls='eza --group-directories-first'
alias ll='eza --long --group-directories-first --header --git'
alias la='eza -la --no-user --group-directories-first --time-style long-iso --header --git'

# Set EDITOR
export EDITOR=helix


# STARSHIP MUST GO AT END OF ZSHRC
eval "$(starship init zsh)"
