#!/bin/bash

# Plugins
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# PATH configuration
export PATH="$HOME/bin:$HOME/.cargo/bin:$PATH"


# ALIAS stuff
alias hx='helix'

# Define eza aliases only if eza is installed
if command -v eza >/dev/null 2>&1; then
    alias ls='eza --group-directories-first'
    alias ll='eza --long --group-directories-first --header --git'
    alias la='eza -la --no-user --group-directories-first --time-style long-iso --header --git'
fi


# Set EDITOR
export EDITOR=helix


# STARSHIP MUST GO AT END OF ZSHRC
eval "$(starship init zsh)"
